### ISSUE TITLE
Merge image files as well?

### ISSUE THREAD

**Issue by samwilson** [OpenBuildings/asset-merger#19]
Is it within the scope of this module to handle the image files as well as JS and CSS? I am using this for module deployment, so need to be able to keep the images in non-web-accessible locations, and have them copied to the assets directory under docroot.

Anyone done this already? :-)

Thanks!

**Comment by piotrgolasz** [comment]
This is way out of scope for this module. I think you can get around this by having your assets (images) for example in "assets" folder, and your compiled assets in "compileassets" folder, if in your css files you hardcode path to image files, f.ex. "/assets/img/image.png", then after compiling the path would persist to original location. Other option would to base64 encode images in your css files.
