### ISSUE TITLE
Support for Kohana 3.3 PSR-0

### ISSUE THREAD

**Issue by theninthnode** [OpenBuildings/asset-merger#29]
I'm planning on upgrading my app to K 3.3 and will need to modify the project to work the uppercase filename requirements of PSR-0.

I don't mind doing the updates and issuing a Pull Request. Just let me know how you want it done. ie. a new branch for 3.3 or a tagged version, etc.

**Comment by hkdobrev** [comment]
@theninthnode Kohana 3.3: https://github.com/OpenBuildings/asset-merger/commit/668e4b7f85996cfee1f34361190e972c31257ac3

**Comment by piotrgolasz** [comment]
Ok, this issue has been solved. Thank you @hkdobrev for fixing and @theninthnode for reporting.
