### ISSUE TITLE
[Security] Subresource Integrity

### ISSUE THREAD

**Issue by piotrgolasz** [OpenBuildings/asset-merger#31]
Would it be possible to add a security feature, so that each link to an asset would have a so called "integrity string". The integrity string is more thoroughly described here:

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Would really appreciate, thanks.

**Comment by hkdobrev** [comment]
@piotrgolasz Hi Piotr! Thank you for your interest in this project! I'm sorry this is not visible well enough, but we're not supporting this project anymore as you can see from the last commit message: https://github.com/OpenBuildings/asset-merger/commit/668e4b7f85996cfee1f34361190e972c31257ac3

However if you use the project and would like to contribute you can create some pull requests and I would make you a collaborator so you're able to maintain the project.

**Comment by piotrgolasz** [comment]
Hi @hkdobrev,
thanks for such quick response.
I'll make two pull requests related to this task and #30.

**Comment by piotrgolasz** [comment]
Hey @hkdobrev, do you accept?

**Comment by hkdobrev** [comment]
@piotrgolasz Hi, thank you for your work on these pull requests! I've written my comments on the respective pull requests. :-)

**Comment by piotrgolasz** [comment]
@hkdobrev I've added multiple hashes - in the config file you can set array as parameter, and that enables it. I added a comment in the config file, however I think we should also change README to reflect recent changes in this and previous pull request.

Haralan, please check it when you can ;)

**Comment by piotrgolasz** [comment]
@hkdobrev ?

**Comment by piotrgolasz** [comment]
Ok, I merged those myself.
