### ISSUE TITLE
Incorrect paths when Kohana not in main directory, ex. example.com/kohana/

### ISSUE THREAD

**Issue by piotrgolasz** [OpenBuildings/asset-merger#34]
The returning path to merged asset doesn't include folder set during setup in bootstrap.php
```
Kohana::init(array(
	'base_url'   => '/kohana/',
	'index_file' => false
));
```

**Comment by piotrgolasz** [comment]
Error when encoding css-paths

**Comment by piotrbaczek** [comment]
Fixed with https://github.com/OpenBuildings/asset-merger/commit/48c9c0ca5f01233fd4c0351d42d7c8d4122fb23b
